### ISSUE TITLE
All grabseqs SRA downloads failing

### ISSUE THREAD

**Issue by cdiener** [louiejtaylor/grabseqs#55]
Looks like some changes on the NCBI side lead to failures in SRA downloads:

```bash
grabseqs sra SRR11733975
Traceback (most recent call last):
  File "/users/cdiener/miniconda3/envs/sra/bin/grabseqs", line 11, in <module>
    sys.exit(main())
  File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/__init__.py", line 58, in main
    metadata_agg = process_sra(args, zip_func)
  File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/sra.py", line 31, in process_sra
    metadata_agg)
  File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/sra.py", line 97, in get_sra_acc_metadata
    run_col = lines[0].index("Run")
ValueError: 'Run' is not in list
```

This seems to be caused by a hardcoded address to download the SRA manifest that is not reachable anymore.

**Comment by AntonioBaeza** [comment]
Having exactly the same issue (tried a few min ago)

**Comment by Zeroo11** [comment]
same issue

**Comment by louiejtaylor** [comment]
Thanks for reporting the issue!

I'll try to figure out a workaround (and see if I can get the automated tests back to passing while I'm at it).

**Comment by cdiener** [comment]
You can also request JSON from esearch which should be easier to convert with Python, for instance for your example: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&term=PRJNA836386&retmax=999&retmode=json .

**Comment by GitUser42** [comment]
Hello :) Is there any workaround until this will be fixed?

**Comment by zhengjxj** [comment]
> Looks like some changes on the NCBI side lead to failures in SRA downloads:
> 
> ```shell
> grabseqs sra SRR11733975
> Traceback (most recent call last):
>   File "/users/cdiener/miniconda3/envs/sra/bin/grabseqs", line 11, in <module>
>     sys.exit(main())
>   File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/__init__.py", line 58, in main
>     metadata_agg = process_sra(args, zip_func)
>   File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/sra.py", line 31, in process_sra
>     metadata_agg)
>   File "/users/cdiener/miniconda3/envs/sra/lib/python3.7/site-packages/grabseqslib/sra.py", line 97, in get_sra_acc_metadata
>     run_col = lines[0].index("Run")
> ValueError: 'Run' is not in list
> ```
> 
> This seems to be caused by a hardcoded address to download the SRA manifest that is not reachable anymore.

Try replacing /usr/local/lib/python3.6/site-packages/grabseqslib/sra.py line 94 with 
metadata = requests.get("https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/sra-db-be.cgi?rettype=runinfo&term="+pacc)

**Comment by AntonioBaeza** [comment]
Thanks. I replaced the info in the file you indicated and is working again!

**Comment by xiachenrui** [comment]
Thanks ! @zhengjxj

**Comment by AMMHasan** [comment]
Hi, is grabseqs sra facing the same problem? what would be the solution this time?
