### ISSUE TITLE
Grabseqs error

### ISSUE THREAD

**Issue by xsq2022** [louiejtaylor/grabseqs#56]
Hi,
I met this problem when I used grabseqs.
![image](https://user-images.githubusercontent.com/101613081/200232987-dec7f4a4-78e5-4f5f-84b3-7efc91fed47b.png)
Traceback (most recent call last):
  File "/media/home/user05/anaconda3/envs/python36/bin/grabseqs", line 11, in <module>
    sys.exit(main())
  File "/media/home/user05/anaconda3/envs/python36/lib/python3.6/site-packages/grabseqslib/__init__.py", line 58, in main
    acclist, metadata_agg = get_sra_acc_metadata(sra_identifier, args.outdir, args.list, not args.SRR_parsing, metadata_agg)
  File "/media/home/user05/anaconda3/envs/python36/lib/python3.6/site-packages/grabseqslib/sra.py", line 52, in get_sra_acc_metadata
    run_col = lines[0].index("Run")
ValueError: 'Run' is not in list
Could you please tell me how to solve this problem? Thanks.

**Comment by deyuanyang** [comment]
same

**Comment by AntonioBaeza** [comment]
same problem than Nov 2022: 

(grabseqs) ant@hillary:~/LemonSharkGSS$ grabseqs sra SRR23340818 -t 12
Traceback (most recent call last):
  File "/home/ant/miniconda3/envs/grabseqs/bin/grabseqs", line 11, in <module>
    sys.exit(main())
  File "/home/ant/miniconda3/envs/grabseqs/lib/python3.7/site-packages/grabseqslib/__init__.py", line 58, in main
    metadata_agg = process_sra(args, zip_func)
  File "/home/ant/miniconda3/envs/grabseqs/lib/python3.7/site-packages/grabseqslib/sra.py", line 31, in process_sra
    metadata_agg)
  File "/home/ant/miniconda3/envs/grabseqs/lib/python3.7/site-packages/grabseqslib/sra.py", line 97, in get_sra_acc_metadata
    run_col = lines[0].index("Run")
ValueError: 'Run' is not in list
(grabseqs) ant@hillary:~/LemonSharkGSS$


At that time, I followed your (below) suggestion and it went back to work: 
Try replacing /usr/local/lib/python3.6/site-packages/grabseqslib/sra.py line 94 with
metadata = requests.get("https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/sra-db-be.cgi?rettype=runinfo&term="+pacc)

Any new suggestion? Thank you!

**Comment by xsq2022** [comment]
It didn't work.

**Comment by LeeYEAH2** [comment]
[sra.txt](https://github.com/louiejtaylor/grabseqs/files/10894627/sra.txt)
rename this txt with sra.py and copy it to /yourpathto/grabseqslib/. replacing the former one will solve the problem for now. It is caused by the replacement of trace.ncbi I suppose. If it doesn't work again, just check whether the path https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be is still working and find a new one.

**Comment by chansigit** [comment]
> 

doesn't work again

**Comment by chansigit** [comment]
```
metadata = requests.get("https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/runinfo?acc="+pacc) 
```
seems work

**Comment by AntonioBaeza** [comment]
Thank you chansigit, it is working again

**Comment by UmerFarooq17** [comment]
if someone is facing this issue now, then try replacing 
/usr/local/lib/python3.6/site-packages/grabseqslib/sra.py **line 45** with
metadata = requests.get("[https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/sra-db-be.cgi?rettype=runinfo&term="+pacc](https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/sra-db-be.cgi?rettype=runinfo&term=%22+pacc))

**Comment by louiejtaylor** [comment]
Sorry to handle this so slowly, life got in the way. Fixed in the latest version (1.0) and will deploy to pypi and conda shortly
