### ISSUE TITLE
 grabseqs sra -l PRJDB5400 pigz not found, using gzip Traceback (most recent call last):   File "/home/tools/anaconda3/bin/grabseqs", line 8, in <module>     sys.exit(main())   File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/__init__.py", line 58, in main     metadata_agg = process_sra(args, zip_func)   File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/sra.py", line 27, in process_sra     acclist, metadata_agg = get_sra_acc_metadata(sra_identifier,   File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/sra.py", line 97, in get_sra_acc_metadata     run_col = lines[0].index("Run") ValueError: 'Run' is not in list

### ISSUE THREAD

**Issue by Damianyangyang** [louiejtaylor/grabseqs#57]
when I use the command "grabseqs sra -l PRJDB5400", I have some errors.
pigz not found, using gzip
Traceback (most recent call last):
  File "/home/tools/anaconda3/bin/grabseqs", line 8, in <module>
    sys.exit(main())
  File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/__init__.py", line 58, in main
    metadata_agg = process_sra(args, zip_func)
  File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/sra.py", line 27, in process_sra
    acclist, metadata_agg = get_sra_acc_metadata(sra_identifier,
  File "/home/tools/anaconda3/lib/python3.8/site-packages/grabseqslib/sra.py", line 97, in get_sra_acc_metadata
    run_col = lines[0].index("Run")
ValueError: 'Run' is not in list

**Comment by AntonioBaeza** [comment]
yes, just used grabseqs and I have a similar message

**Comment by louiejtaylor** [comment]
Sorry to handle this so slowly, life got in the way. Fixed in the latest version (1.0) and will deploy to pypi and conda shortly
